version: "3.5"
services:
    node:
        image: node:17.4
        working_dir: "/app"
        environment:
            - HOST=0.0.0.0
            - PORT=80
        user: "node"
        volumes:
            - "./:/app"
        networks:
            - ychanter
        command: "node .output/server/index.mjs"
        restart: "always"

networks:
    ychanter:
        name: ychanter-network
        external: true
